version: "3"
services:
  web:
    build: app
    container_name: php-webserver
    ports: 
      - '80:80'
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - localdb
    networks: 
      - webserver
      
  localdb:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - mysqldb:/var/lib/mysql
    networks: 
      - webserver

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=localdb
    networks: 
      - webserver


  
volumes: 
  mysqldb:
    
networks:
  webserver:
    name: ws_network